# This file was generated by GoReleaser. DO NOT EDIT.
cask "remetric" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f18504a35cdba4b045f256a54ef183f2fb23cb7ffcbdd6d2b46ee70e69c26899"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9af2e7028d8e3f6023e2c7677fb3f4e48400e79a3b121e4eb6834664dc0ca4b1"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b8a8e1f15a1febc073f51ecba8e8fd043a986e595462650d0398ad661a33997"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66d41d0bf33da3718a5a0272cb2474fae511def4beb28cfbddfa50a09a7aaaa3"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remetric"
  desc "Re-metric your stack - find waste in Prometheus, Grafana & Loki"
  homepage "https://remetric.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remetric"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remetric"]
    end
  end

  # No zap stanza required

end
