# This file was generated by GoReleaser. DO NOT EDIT.
cask "remetric" do
  version "0.1.0-rc.8"

  on_macos do
    on_intel do
      sha256 "5ef42a507c45f00f5ee85da10510df25fb1b447d3543ad4b61ed450541a5507c"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de484d475646800c39737e2cc5e69e084ebad14928921b8b8d083bed7fb53973"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7d848dee7087ad2f29eae5f92b527619a297774410adb2e622bdc59dfbca109"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "583b234f2829a5328a03846b1690ad833eebf86fbf40a11a49d0baef77402f52"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remetric"
  desc "Re-metric your stack - find waste in Prometheus, Grafana & Loki"
  homepage "https://remetric.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remetric"

  # No zap stanza required

end
