# This file was generated by GoReleaser. DO NOT EDIT.
cask "remetric" do
  version "0.1.0-rc.9"

  on_macos do
    on_intel do
      sha256 "15d937c3754e30b33f3b81642513e215222472b757e3cf753f16ffbbcfb28071"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d25a458d609ad6247f6790834e5cd2d373287378265599c8a4b274155e4d8827"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "360cd776739909939d1242d3245ef85db6972ee144055a1e6e0e326cf31c42da"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "36db02df7951bb6b646a24e96b357bba2bb63749ce993a57ed8e907ca221891e"
      url "https://github.com/remetric-dev/remetric/releases/download/v#{version}/remetric_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remetric"
  desc "Re-metric your stack - find waste in Prometheus, Grafana & Loki"
  homepage "https://remetric.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remetric"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remetric"]
    end
  end

  # No zap stanza required

end
